/*
  * This Java source file was generated by the Gradle 'init' task.
  */
  package jp.ac.uryukyu.ie.e215740;

  import org.junit.jupiter.api.Test;
  import static org.junit.jupiter.api.Assertions.*;
  /**
    * BaseballTestクラス
    * 
    */
  
  class BaseballTest{
      @Test void BaseballTest(){
          boolean testgameSet = true;
          Baseball baseballTest = new Baseball();
          while(baseballTest.strikeOut == true){
              baseballTest.batter();
          }
          assertEquals(baseballTest.gameSet ,testgameSet);
      }
  }